backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

# when using the default proxy server port
local_backend: true

media_folder: "img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow

collections:
  - label: "Projects"
    name: "projects"
    folder: "_projects"
    create: true
    fields:
      - {label: "Layout", name: "layout", default: "project", widget: "hidden"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Background Video", name: "bg_video", widget: "string", required: false}
      - {label: "Misc Layout", name: "misc_layout", widget: "boolean", default: false, required: false}
      - { label: 'Color', name: 'color', widget: 'color', enableAlpha: true, allowInput: true }
      - label: "Sections"
        name: "sections"
        widget: "list"
        summary: "Section {{section_title}}"
        fields:
          - {label: "Section Title", name: "section_title", widget: "string", required: false}
          - label: 'Header'
            name: 'header'
            widget: object
            collapsed: true
            summary: '{{fields.text_one}}'
            fields:
              - {label: "One", name: "text_one", minimal: true, widget: "markdown", required: false}
              - {label: "Two", name: "text_two", minimal: true, widget: "markdown", required: false}
              - {label: "Centererd", name: "header_centered", minimal: true, widget: "boolean", default: false, required: false}
          - label: "Media Gallery"
            name: "media_gallery"
            widget: "list"
            add_to_top: true
            minimize_collapsed: true
            summary: '{{fields.quote}} - {{fields.author.name}}'
            types:
              - label: 'Image'
                name: 'image'
                widget: object
                summary: '{{fields.img}}'
                field: {label: "Image", name: "img", widget: "image", required: false}
              - label: 'Video'
                name: 'video'
                widget: object
                summary: '{{fields.vid}}'
                fields: 
                  - {label: "Video", name: "vid", widget: "string", required: false}
                  - {label: "Background", name: "background", widget: "boolean", default: false, required: false}
              - label: 'Text'
                name: 'text'
                widget: object
                summary: '{{fields.txt}}'
                field: {label: "Text", name: "txt", minimal: true, widget: "markdown", required: false}
          - label: "Column count"
            name: "col_count"
            widget: "number"
            default: 2
            value_type: "int"
            min: 1
            max: 3
            step: 1
          - {label: "Backgrond Color", name: "bg_color_check", widget: "boolean", default: false}
  - name: settings
    label: Settings
    files:
    - name: about_page
      label: About Page
      file: about.md
      fields:
        - {label: "Layout", name: "layout", default: "about", widget: "hidden"}
        - {label: "info", name: "info", minimal: true, widget: "markdown", required: false}
        - {label: "Image", name: "img", widget: "image", required: false}
        - label: "Resume"
          name: "resume"
          widget: "file"
          required: false
          media_library:
            config:
              multiple: true
        - label: Links
          name: links
          widget: list
          fields: 
            - {label: "Link Title", name: "link_title", widget: "string", required: false}
            - {label: "Link URL", name: "link_url", widget: "string", required: false}
    - name: collectionOrder
      label: Collection Order
      file: _data/collectionOrder.yml
      fields:
        - label: Collection
          name: collection
          widget: list
          fields: 
            - label: Collection Name 
              name: collectionName 
              widget: relation
              collection: projects
              searchFields: [title]
              valueField: title
              default: projects

